-- queries

Here are the SQL queries to solve the given problems:

-- Find the item that has minimum weight

SELECT ITEMNO, DESCRIPTION, WEIGHT
FROM ITEMS
WHERE WEIGHT = (SELECT MIN(WEIGHT) FROM ITEMS);

-- Find the different warehouses in “Pune”

SELECT WID, WNAME, LOCATION
FROM WAREHOUSES
WHERE CITY = 'Pune';

-- Find the details of items ordered by a customer “Mr. Patil”

SELECT I.ITEMNO, I.DESCRIPTION, O.ORDERED_QUANTITY
FROM ITEMS I
INNER JOIN ORDERS_ITEMS OI ON I.ITEMNO = OI.ITEMNO
INNER JOIN ORDERS O ON OI.ONO = O.ONO
INNER JOIN CUSTOMER C ON O.CNO = C.CNO
WHERE C.CNAME = 'Mr. Patil';

-- Find a Warehouse which has maximum stores

SELECT W.WID, W.WNAME, COUNT(S.SID) AS STORE_COUNT
FROM WAREHOUSES W
LEFT JOIN STORES S ON W.WID = S.WID
GROUP BY W.WID, W.WNAME
ORDER BY STORE_COUNT DESC
LIMIT 1;

-- Find an item which is ordered for a minimum number of times

SELECT I.ITEMNO, I.DESCRIPTION, COUNT(OI.ONO) AS ORDER_COUNT
FROM ITEMS I
LEFT JOIN ORDERS_ITEMS OI ON I.ITEMNO = OI.ITEMNO
GROUP BY I.ITEMNO, I.DESCRIPTION
HAVING ORDER_COUNT = (SELECT MIN(ORDER_COUNT) FROM (SELECT COUNT(ONO) AS ORDER_COUNT FROM ORDERS_ITEMS GROUP BY ITEMNO) AS T);

-- Find the detailed orders given by each customer:

SELECT C.CNO, C.CNAME, O.ONO, O.ODATE, I.ITEMNO, I.DESCRIPTION, OI.ORDERED_QUANTITY
FROM CUSTOMER C
LEFT JOIN ORDERS O ON C.CNO = O.CNO
LEFT JOIN ORDERS_ITEMS OI ON O.ONO = OI.ONO
LEFT JOIN ITEMS I ON OI.ITEMNO = I.ITEMNO
ORDER BY C.CNO, O.ONO, I.ITEMNO;


