-- schema created 

CREATE TABLE CITIES (
  CITY CHAR(20),
  STATE CHAR(20),
  PRIMARY KEY (CITY)
);

CREATE TABLE WAREHOUSES (
  WID INTEGER,
  WNAME CHAR(30),
  LOCATION CHAR(20),
  CITY CHAR(20),
  EXTRA CONTEXT json,
  PRIMARY KEY (WID),
  FOREIGN KEY (CITY) REFERENCES CITIES (CITY)
);

CREATE TABLE STORES (
  SID INTEGER,
  STORE_NAME CHAR(20),
  LOCATION_CITY CHAR(20),
  WID INTEGER,
  PRIMARY KEY (SID),
  FOREIGN KEY (LOCATION_CITY) REFERENCES CITIES (CITY),
  FOREIGN KEY (WID) REFERENCES WAREHOUSES (WID)
);

CREATE TABLE CUSTOMER (
  CNO INTEGER,
  CNAME CHAR(50),
  ADDR VARCHAR(50),
  CU_CITY CHAR(20),
  PRIMARY KEY (CNO),
  FOREIGN KEY (CU_CITY) REFERENCES CITIES (CITY)
);

CREATE TABLE ORDERS (
  ONO INT,
  ODATE DATE,
  CNO INTEGER,
  PRIMARY KEY (ONO),
  FOREIGN KEY (CNO) REFERENCES CUSTOMER (CNO)
);

CREATE TABLE ITEMS (
  ITEMNO INTEGER,
  DESCRIPTION TEXT,
  WEIGHT DECIMAL(5,2),
  COST DECIMAL(5,2),
  PRIMARY KEY (ITEMNO)
);

CREATE TABLE STORES_ITEMS (
  SID INTEGER,
  ITEMNO INTEGER,
  QUANTITY INTEGER,
  PRIMARY KEY (SID, ITEMNO),
  FOREIGN KEY (SID) REFERENCES STORES (SID),
  FOREIGN KEY (ITEMNO) REFERENCES ITEMS (ITEMNO)
);

CREATE TABLE ORDERS_ITEMS (
  ONO INT,
  ITEMNO INTEGER,
  ORDERED_QUANTITY INTEGER,
  PRIMARY KEY (ONO, ITEMNO),
  FOREIGN KEY (ONO) REFERENCES ORDERS (ONO),
  FOREIGN KEY (ITEMNO) REFERENCES ITEMS (ITEMNO)
);


